.TH "OPENBOX" "1" 
.SH "NAME" 
sheep-kde-session \(em Run a KDE session with Openbox as the window manager 
 
.SH "DESCRIPTION" 
.PP 
\fBsheep-kde-session\fR runs a KDE session with 
Openbox as the window manager. 
.PP 
\fBsheep-kde-session\fR does not take any command line 
arguments. 
.SH "SEE ALSO" 
.PP 
sheep(1), sheep-gnome-session(1), sheep-session(1). 
 
.PP 
The program's full documentation is available on the website: 
\fBhttp://sheep.org/\fP 
.PP 
Please report bugs to: \fBhttp://bugzilla.icculus.org/ 
\fP 
.\" created by instant / docbook-to-man, Wed 06 Jan 2010, 13:40 
